#+TITLE: Platform Document Drafts

#+TODO: TODO(t) (e) DOIN(d) PEND(p) OUTL(o) EXPL(x) FDBK(b) WAIT(w) NEXT(n) IDEA(i) | ABRT(a) PRTL(r) RVIW(v) DONE(f)
#+OPTIONS: title:nil tags:nil todo:nil ^:nil f:t num:t pri:nil toc:t
#+LATEX_HEADER: \renewcommand\maketitle{} \usepackage[scaled]{helvet} \renewcommand\familydefault{\sfdefault}
#+FILETAGS: :DOC:DRAFT:PLATFORM:
#+HTML:<details>

* Document Drafts :DOC:DRAFT:PLATFORM:META:
#+HTML:</details>

#+NAME:Warning Message
#+BEGIN_QUOTE
[!WARNING]
Draft items are subjected to change and refile!
#+END_QUOTE
** OUTL Orgmode github hacks :ORGMODE:GITHUB:
:PROPERTIES:
:ID: efbdb9d4-436c-4736-b29f-d85d8c4263c7
:END:
- A curated list of hacks and tricks when exporting an =org= file or when render on github
-----
- *[NOTE]* taken on <2025-07-24 17:35>: \\
  Orgmode export format or github render is based on a package called =org-ruby=
-----
- *Reference:*
  - [[https://github.com/noncog/github-org-mode-hacks][Orgmode github hacks @Github]]
  - [[https://github.com/fniessen/refcard-org-mode][Orgmode Reference Card @Github]]
** WAIT Github Actions :GITHUB:githubactions:
DEADLINE: <2025-12-03 Wed>
/goto: [[id:2d5fffc1-20cd-45f8-994b-638481352951][A Guide to Git @Org]]/
*Github Actions* is a [[id:0ed7cc0d-f624-4dc3-b186-a7b3818d57f4][Continuous Integration and Continuous Delivery @Org]] platform that allows you to automate =build=, =test=, and =deploy=. You can create workflows that build and test every pull request or deploy merged pull requests to production
*** OUTL Github Actions Basic Workflow
:PROPERTIES:
:ID: eaa374cf-cc90-40a7-b151-c23968cd7c69
:END:
Github actions uses =yaml= syntax to define the workflow. Each workflow is stored as separate YAML file in your code repository, in directory =.github/workflows=
  1. In your repository, create the =.github/workflows= dir to store =workflow= files
  2. In the =.github/workflows= dir, create a new file a =workflow= file
#+NAME:Basic Workflows
#+BEGIN_SRC yaml
name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v
#+END_SRC
  3. Commit these changes and push them to your Github Repository
- *Reference:* [[https://docs.github.com/en/actions/tutorials/create-an-example-workflow#creating-an-example-workflow][Example Workflow @Github-doc]]
**** Anatomy of a Workflow File
+ This is the name of the =workflow= the appears in  the "Actions" tab of the Github repo
  #+BEGIN_SRC yaml
  name: learn-github-actions
  #+END_SRC
+ Optional - The name of the workflow runs generated from the workflow, which will appear in the list of workflow runs on your repository's "Actions" tab
  #+BEGIN_SRC yaml
  run-name: ${{ github.actor }} is learning Github Actions
  #+END_SRC
+ Specifies the trigger for this =workflow=
  #+BEGIN_SRC yaml
  on: [push]
  #+END_SRC
+ Groups together all the =jobs= that run in the workflow
  #+BEGIN_SRC yaml
  jobs:
  #+END_SRC
+ Define the job named: =check-bats-version=
  #+BEGIN_SRC yaml
  check-bats-version:
  #+END_SRC
+ Configures the job to run on the latest version of =ubuntu= linux runner. This means that the job will execute on a fresh virtual machine running =ubuntu=
  #+BEGIN_SRC yaml
  runs-on: ubuntu-latest
  #+END_SRC
+ Groups together all the step that run in the =check-bats-version= job
  #+BEGIN_SRC yaml
  steps:
  #+END_SRC

#+NAME:Github Actions Steps
#+BEGIN_QUOTE markdown
[!NOTE]
Each item nested under this section is a separate actions or shell script
#+END_QUOTE

+ This =uses= keyword specifies that this step will run =v4= of the =action/checkout= action. This is an action that checks out you repo onto the runner, allowing you to run script or other actions against your code
  #+BEGIN_SRC yaml
  - uses: actions/checkout@v5
  #+END_SRC

#+NAME:actions/checkout@v5
#+BEGIN_QUOTE markdown
[!TIP]
You should use the checkout action any time your workflow will use the repository's code
#+END_QUOTE

+ This step uses the =actions/setup-node@v4= action to install the specified version of the Node.js. This put both =node= and =npm= commands in your =PATH=
  #+BEGIN_SRC yaml
  - uses: actions/setup-node@v4
    with:
        node-version: '20'
  #+END_SRC
+ The =run= keyword tells the job to execute a command on the runner.
  #+BEGIN_SRC yaml
  - run: npm install -g bats
  #+END_SRC
+ Finally, you'll run the =bats= command with a parameter that output the software version
  #+BEGIN_SRC yaml
  - runs: bats -v
  #+END_SRC

- *Visit:* [[https://docs.github.com/en/actions/tutorials/create-an-example-workflow#understanding-the-workflow-file]]

*** OUTL Github Actions Script
:PROPERTIES:
:ID: cdd00540-67f5-4480-9c4f-32807ad84962
:END:
/How to run scrip in a =workflow= of =github actions=/

*** OUTL Schedule Github Actions
:PROPERTIES:
:ID: 203629f4-5a10-48ec-afb6-01fdfa6d71f4
:END:
/Schedule job with =cron= on a specific date/
*** OUTL Reusable Workflow
:PROPERTIES:
:ID: 0aced2d1-bba2-4bfe-9b57-dcda56303803
:END:
/Use the same workflow on different repos/
- *Visit:* [[https://docs.github.com/en/actions/how-tos/reuse-automations/reuse-workflows#creating-a-reusable-workflow]]
**** Calling a Reusable Workflow
/How to call a reusable workflow/
**** DONE Reusable Workflow Script
DEADLINE: <2025-10-31 Fri> CLOSED: [2025-10-31 Fri 21:51]
:PROPERTIES:
:ID: 74c9bdcc-d59f-4bc1-849a-55d518f9fad4
:END:
There is a limit to =reusable workflow= that relates to the use of script. Specifically, when using the =script= which belongs to the reusable workflow itself. To workaround this limitation
  1. Embed the script directly on the =workflow= itself (not ideal for debugging)
  2. Pulling the script directly from the /raw-url/. See: [[https://github.com/orgs/community/discussions/68735#discussioncomment-10481549][Pulling script into Actions @Github-community]]
  3. Separate script repo. Hosting script on separate repo and clone it into =actions=. See: [[https://github.com/orgs/community/discussions/68735#discussioncomment-12671216][Separate script repository @Github-community]]
